name: Update Kaggle Dataset Manual

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  update-dataset:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install Kaggle API
      run: |
        pip install kaggle
    
    - name: Setup Kaggle credentials
      run: |
        mkdir -p ~/.kaggle
        echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
    
    - name: Create dataset metadata
      run: |
        cat > dataset-metadata.json << EOF
        {
          "title": "Streetfighters RL Code",
          "id": "vader773/streetfighters-rl-code",
          "licenses": [{"name": "CC0-1.0"}]
        }
        EOF
    
    - name: Update Kaggle dataset
      run: |
        kaggle datasets version -p . -m "Auto-update from GitHub commit ${{ github.sha }}"